# Telegraf configuration for MQTT → InfluxDB v2

[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = "1ns"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["wtp/+/+/+/observation"]
  qos = 0
  connection_timeout = "30s"
  client_id = "telegraf-consumer"
  persistent_session = false
  data_format = "json"
  json_time_key = "ts"
  json_time_format = "RFC3339"
  json_timezone = "UTC"
  json_name_key = "measurement"
  tag_keys = ["site_id", "asset_id", "sensor_id",  "value", "unit", "quality","source", "raw_tag", "parameter_type", "component_type"]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "hydros"
  bucket = "wtp"

